#!/bin/sh

CONTAINER_NAME="$(basename ${BASH_SOURCE[0]})"
CONTAINER_OUTPUT="/u/containers/$CONTAINER_NAME"
CONTAINER_SOURCE=

# Embed into an initramfs
EMBED=true

# Use wily to support lxd
DISTRO=wily

network_packages="network-manager,iproute2,bind9-host,iputils-ping,ifupdown" # not sure what to do here

# Sets up the default packages to install
PACKAGES="lxc,lxd,lxd-client,openssh-server,initramfs-tools,live-boot,${network_packages}"

# Extra packages to be installed after debootstrap
EXTRA_PACKAGES=""

# Packages to blacklist during debootstrap
BLACKLIST_PACKAGES=""

customize()
{
  cexec apt-get install --no-install-recommends -y linux-firmware linux-image-3.19.0-31-generic
}
