#!/bin/sh

CONTAINER_NAME="$(basename ${BASH_SOURCE[0]})"
CONTAINER_OUTPUT="/u/containers/$CONTAINER_NAME"
CONTAINER_SOURCE=

# Embed into an initramfs
EMBED=true

# Use wily to support lxd
DISTRO=wily

network_packages="network-manager,iproute2,bind9-host,iputils-ping,ifupdown" # not sure what to do here

# Sets up the default packages to install
PACKAGES="lxc,lxd,lxd-client,openssh-server,initramfs-tools,live-boot,${network_packages}"

EXCLUDE_PATTERN=('boot/*' 'vmlinuz' 'initrd.img')

# Extra packages to be installed after debootstrap
EXTRA_PACKAGES="linux-firmware linux-image-3.19.0-31-generic"

# Packages to blacklist during debootstrap
BLACKLIST_PACKAGES="" # this is probably a bad idea as it's probably needed

DESKTOP="xorg,vim" #i3 deb http://debian.sur5r.net/i3/ wily universe
