# Container name and home
[ -z "$CONTAINER_HOME" ] && CONTAINER_HOME='/u/lxc'
CONTAINER_NAME=
CONTAINER_OUTPUT=
CONTAINER_SOURCE=

## FIXME - move to user rc file

# Admin settings (not secure)
ADMIN_USERNAME=console
ADMIN_PASSWORD=cvisor

ADMIN_PUBKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCd9MR4lTtEreJqyXWjVRxxMzYMUxYTLr0PMDkY52BgiBVHL+JY8Pbx7hcEaSkd9wMlun6Jverq3QYXUk+1FOOBJwC/ATZloCav0sqn9/37QrMvBPcwHgH054abKZJ0ctkpBTUa7AS+IRtco30i7J7Irzr6jbRvZ2BO6Nh1TlhGBQ0y5IOEMBhWMq9sUXBNmsNxDSGaabEX83Dkgk4pkTtr4Sk0oUpWWI94E3zttYAP6e7gRhiOn6LeYiDfTvIRkN9c/scErs1W3Pa6WY0EWLR7TeVtSWVEo5QIYbJbXRJTOCWyoMc8u5f9c82kIPG+4Ufe9wLUd7t2kVUDh6v89Ord daleha@Zenframe"

# Extra kernel arguments
KERNEL_ARGS=""
