#!/bin/sh

CONTAINER_NAME="$(basename ${BASH_SOURCE[0]})"
CONTAINER_OUTPUT="/u/containers/$CONTAINER_NAME"
CONTAINER_SOURCE=

# Embed into an initramfs
EMBED=true

DISTRO=trusty

network_packages="network-manager iproute2 bind9-host iputils-ping ifupdown" # not sure what to do here

# Sets up the default packages to install
PACKAGES="openssh-server,initramfs-tools,live-boot,lvm2"

# Extra packages to be installed after debootstrap
EXTRA_PACKAGES="vim ${network_packages}"

# Packages to blacklist during debootstrap
BLACKLIST_PACKAGES=""

customize(){
  script_path="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ))/util/install.sh" 
  cp ${script_path} "${CONTAINER_HOME}/${CONTAINER_NAME}/rootfs/install.sh"
  cexec apt-get install -y linux-generic-lts-vivid
}
